# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.6
#  - 7.0

rvm:
 # - 2.2.3
  - 1.9.3
  
sudo: required
dist: trusty
group: edge

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3f2dee1a025739ac5da7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

before_install:
 - chmod +x ./travis-ci/*.sh

# prepare travis ci for the build process
install:
 - ./travis-ci/install-composer.sh
 - npm install
 
# linters
before_script:
 - ./travis-ci/setup-db.sh

# execute tests
script:
 - ./travis-ci/tests.sh
