# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
# aliased to a recent 5.6.x version
  - 5.6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3f2dee1a025739ac5da7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  
# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS churchcrm_test;" -uroot; fi
  - cd ./src
  - composer install  
  - cd ..

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
  - if [[ "$DB" == "mysql" ]]; then mysql churchcrm_test < src/mysql/install/Install.sql -uroot; fi
  - tests/LineEndings.sh
  ##- phpunit --configuration phpunit_$DB.xml --coverage-text
