services:
  webserver-test:
    volumes:
      - ../src:/var/www/html/churchcrm
    environment:
      - CHURCHCRM_SUBDIR=churchcrm

  # Ensure new-system webserver also mounts to subdir when using the subdir overlay
  webserver-new-system:
    volumes:
      - ../src:/var/www/html/churchcrm
    environment:
      - CHURCHCRM_SUBDIR=churchcrm
